name: EssentialsLT
main: biz.mcsistemas.essentialslt.EssentialsLT
author: Fernando Brasil
version: 1.0
commands:
    tpa:
    tp:
    tpc:
    tpaccept:
    tphere:
        aliases: [s]
    setwarp:
    delwarp:
    warp:
    invsee:
    fly:
    god:
    hat:
    eip:
    kit:
    alert:
     aliases: [say]
    ELTreload:
    cores:
    spawn:
    reparar: